### ISSUE TITLE
Lag time in new module releases being available in registry is painful

### ISSUE THREAD

**Issue by Gowiem** [opentofu/registry#241]
### Thank you for reporting an issue.

My team and I maintain a few small modules @ https://github.com/masterpointio. These modules have seamlessly been available in the OpenTF registry since we switched one of our projects to tofu. 

One thing I just noticed however is that when we publish a new release, e.g. https://github.com/masterpointio/terraform-aws-tailscale/releases/tag/1.0.0, it does not show up in the registry immediately and we get the following error when trying to use that new release tag in our consuming root module: 

> There is no available version of module "[registry.opentofu.org/masterpointio/tailscale/aws](http://registry.opentofu.org/masterpointio/tailscale/aws)" (main.tf:1) which matches the given version constraint. The newest
> available version is 0.5.0.

[It seems after discussion in Slack, that this because there should be some expected lag time in the registry picking up new releases from modules in the registry](https://opentofucommunity.slack.com/archives/C05R0FD0VRU/p1708463312128849).

Makes total sense, but I would like to raise the concern around this workflow ("Module developer publishes new release => Release is picked up by Tofu Registry => Module developer (or other consumer) can consume that release") needing to be faster as this is painful. Few things come to mind: 

1. For folks like me that maintain their own modules (and/or 3rd party module libraries like https://github.com/cloudposse) because this is a very common workflow, so expecting long lag times before new releases are available means blocking development time.
2. This is not only an issue for module developers as it could easily be a random module user goes to consume a new child module in their project, copies a very recent latest release tag from GH into their project, and then suddenly they're left thinking that module version isn't available, they've done something wrong, or that the module in question doesn't support OpenTofu. 

I believe this needs to be better addressed. In the short-term, a better error message that lets consumers know of the lag time in module releases being available in the registry would be a good start until a long-term solution can be put in place. Otherwise, we'll find many people thinking the Tofu registry is broken. 

Happy to discuss options!

### OpenTofu Version

```shell
OpenTofu v1.6.1
on linux_arm64
```

### OpenTofu Configuration Files

N/A

**Comment by Yantrio** [comment]
Hi @Gowiem , Thanks for raising this!

Sadly you were really unfornunate in that our hourly update failed at the same time that you were looking to publish a new version of your module, and for this we're really sorry and we are making sure we find ways to avoid this again in the future.

## Possible solutions/mitigations

I think we have a few of options here where we have the possibility of mitigating this.

### Option 1 - Increase cycles
Because the development lifecycle/loop is tighter for modules, we can sync those more often separate from the modules. This could give us a cycle time of 10 or 15 minutes if everything goes to play.

### Option 2 - Allow manual refreshing somehow
I love the implementation used by pkg.go.dev (For example, see https://pkg.go.dev/github.com/opentofu/opentofu@v1.6.999999999)

Here you can click a button to refresh the versions that are fetched.

I think it may be irrational to expect end users to kick off github actions, but we can investigate some flows that may work for us. Ie a small wrapper application where a user can request an update and it kicks off a github action in the background. 

The code to support updating a single module is in the codebase if I remember correctly, so implementing this may not be too difficult.

### Option 3 - Allow some module authors to set up webhooks for an event-driven update

This approach would mean that we install a webhook to get change events on the repository and react to that.

My opinion personally is that this would not scale too well with our current approach, but it's food for thought anyway.

### Option 4 - Smart fancy stuff

Try and identify situations in registry where someone has requested /versions but has not requested a download link afterwards. This is indicative of a module version not being available. From there we could create a "priority queue" where we attempt to update those packages.

I'm not a huge fan of this one for 2 reasons. 
1. We cache heavily in cloudflare, so identifying this would be difficult. 
2. It creates an "unfair" world for modules where some may get updated sooner than others.

**Comment by cam72cam** [comment]
We've gone from a full synchronization taking 2+hours down to 6-15 minutes (with a worst case of 30 minutes).

If that's still not fast enough @Gowiem, feel free to re-open!

**Comment by Gowiem** [comment]
@cam72cam great stuff -- I will keep an eye on this and will reopen if necessary, but those are fantastic numbers and I love to see it. Keep up the awesome work!!
