### ISSUE TITLE
OpenTofu still shows default plugin location as hashicorp/oci ! Is it means opentofu uses "hashicorp" name internally in the OpenTofu code? Will it affect the compliance?

### ISSUE THREAD

**Issue by yogeshlc** [opentofu/registry#329]
### Thank you for reporting an issue.

 tofu init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/oci...
- Installing hashicorp/oci v5.33.0...
- Installed hashicorp/oci v5.33.0 (signed, key ID 1533A49284137CEB)

Providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://opentofu.org/docs/cli/plugins/signing/

### OpenTofu Version

```shell
OpenTofu v1.6.1
on linux_amd64
+ provider registry.opentofu.org/hashicorp/oci v5.33.0
```

### OpenTofu Configuration Files

```hcl
// Snippet of HCL that can be used to help reproduce this problem
```

**Comment by ghost** [comment]
Hey @yogeshlc this is intentional. Hashicorp is still maintaining these providers under the MPL license, the OpenTofu project only builds binaries from the source code but we do not change the code in any form. So, the source and producer of these providers is still Hashicorp.

Should the license of these providers change, we will need to take steps to not ship these binaries anymore and find a way to maintain them, but for the time being, we do not maintain the code separately. However, the binaries are coming from the OpenTofu registry, so you are not violating the Terraform registry's Terms of Service because you are not using it.

Please note that this is, of course, not legal advice, so I cannot comment on your specific compliance needs.

I will close this issue, but feel free to reopen it if your question has not been answered adequately.
