### ISSUE TITLE
hashicorp/aws - merging of IAM policy documents using source_policy_documents does not work as expected

### ISSUE THREAD

**Issue by areis422** [opentofu/registry#753]
### Thank you for reporting an issue.

Merging of `aws_iam_policy_document` using `source_policy_documents` does not work as expected. `override_policy_documents` does seem to work as expected, but I need the "add missing elements" functionality of `source_policy_documents`

### OpenTofu Version

```shell
$ tofu version
OpenTofu v1.7.3
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/aws v5.60.0
```

### OpenTofu Configuration Files

Input documents:
```hcl
data "aws_iam_policy_document" "deny_non_ssl" {
  statement {
    sid    = "deny_non_ssl"
    effect = "Deny"
    principals {
      type        = "*"
      identifiers = ["*"]
    }
    condition {
      test     = "Bool"
      variable = "aws:SecureTransport"
      values   = ["false"]
    }
  }
}

data "aws_iam_policy_document" "s3_bucket_policy" {
  source_policy_documents = [
    data.aws_iam_policy_document.deny_non_ssl.json
  ]
  statement {
    sid     = "deny_non_ssl"
    actions = ["s3:*"]
    resources = [
      aws_s3_bucket.s3_bucket.arn,
      "${aws_s3_bucket.s3_bucket.arn}/*"
    ]
  }
}
```

Expected Output(from `tofu plan` or `tofu apply` as the actual json document):
```hcl
data "aws_iam_policy_document" "s3_bucket_policy" {
  statement {
    sid    = "deny_non_ssl"
    effect = "Deny"
    principals {
      type        = "*"
      identifiers = ["*"]
    }
    actions = ["s3:*"]
    resources = [
      aws_s3_bucket.s3_bucket.arn,
      "${aws_s3_bucket.s3_bucket.arn}/*"
    ]
    condition {
      test     = "Bool"
      variable = "aws:SecureTransport"
      values   = ["false"]
    }
  }
}
```

Actual Output (from `tofu plan` or `tofu apply` as the actual json document):
```hcl
data "aws_iam_policy_document" "s3_bucket_policy" {
  statement {
    sid    = "deny_non_ssl"
    effect = "Allow"
    actions = ["s3:*"]
    resources = [
      aws_s3_bucket.s3_bucket.arn,
      "${aws_s3_bucket.s3_bucket.arn}/*"
    ]
  }
}
```

**Comment by ghost** [comment]
Hi and thank you for the issue. This seems to be a problem with the AWS provider (maintained by HashiCorp) not OpenTofu itself. Unfortunately, we cannot fix bugs in HashiCorp-maintained providers as we are only hosting a lightweight fork for the purposes of building the binaries, but we are not accepting patches for them. Please [open an issue with HashiCorp](https://github.com/hashicorp/terraform-provider-aws/issues) about this problem. I will close this issue, but please feel free to reopen the issue if it turns out that this is a problem with OpenTofu.
